### ISSUE TITLE
Missing FORMAT entry from the report-stahtd stanza in default/transforms.conf

### ISSUE THREAD

**Issue by barrettnet** [fwijnholds/TA-ubiquiti#5]
I'm seeing an error in my logs about the report-stahtd stanza missing a FORMAT entry.

The fix would appear to be to add the following line to the `[report-stahtd]` stanza in the default/transforms.conf

`FORMAT = json::$1`

Note that I've called the extracted field json because that's the name of the SOURCE_KEY used by the report-stahtd-kv stanza to parse the JSON blob.

The issue is present in v1.3.6 of the add-on.

**Comment by fwijnholds** [comment]
Fixed this, thanks for submitting!
